# Generated by Django 3.2.4 on 2022-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='con_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
